- .prettierrc
- app/_utils/supabase/authAPI.ts
- app/login/page.tsx
- app/register/page.tsx
closed #2
supabase 설정 및 email 로그인
없었습니다.
supabase auth api 문서를 참고하였습니다.
(https://supabase.com/docs/reference/javascript/auth-api)
> [Feat/#2] - supabase 설정 및 email 로그인

- .vscode/settings.json
- app/_hooks/useQuery.ts
- app/_types/index.ts
- app/layout.tsx
- app/livekitAPI/get-participant-token/route.ts
- app/main/page.tsx
- app/page.tsx
- app/room/[id]/page.tsx
- package.json
- yarn.lock
closed #8 
livekit 설치 및 마피아 페이지 경로 설정
> [ADD #8] livekit 설치 및 마피아 페이지 경로 설정

- app/_utils/supabase/authAPI.ts
- app/login/page.tsx
closed #12
이메일 로그인 유효성 조건 설정 (유저 이메일의 비밀번호가 맞는지 검사, auth를 통한 로그인 과정 유효성 검사)
router.push() 메서드를 사용하는 과정에서 next/navigation 대신에 next/router를 사용해서 에러가 발생했습니다.
try catch 문에서 catch 문안에 return 문을 입력하지 않아서 코드가 끝까지 실행되는 상황이 발생하였습니다.
그래서 catch 문의 마지막에 return 문을 입력하였습니다.
try catch 문에대해서 좀 더 자세히 알게 되었습니다.
> [Feat/#12] - 이메일 로그인 유효성 조건 설정

- app/room/[id]/page.tsx
```
```
```
```
```
|기능|스크린샷|
[GIF]<img src = "" width="250">|
```
> [Test #20] 테스트 주석 추가

- app/_components/intro/Intropage.tsx
- app/_style/HeaderLogo.ts
- app/_style/Intropage/video.module.css
- app/page.tsx
closed #18 
선생님의 시선이 무서웠어요 
모든게 새롭고 모든게 궁금합니다
> [Feat] intropage layout 생성, 비디오 추가

- app/protected/page.tsx
- app/room/[id]/page.tsx
closed #7 
livekit hooks를 사용하여 유저 전체 및 특정 유저 , 전체 트랙 등을 가져와 사용하였다.
> [Feat #7] 플레이어의 캠 및 오디오 설정 제어

- app/_components/main/roombutton.tsx
- app/room/[id]/page.tsx
> [Fix #6] - 시맨틱 태그 변경, toggle image 추가

- app/_components/intro/Intropage.tsx
- package.json
- yarn.lock
> [Pull #17] 병합완료

- .vscode/settings.json
- app/_components/intro/Intropage.tsx
- app/_components/layout/Footer.tsx
- app/_components/layout/Header.tsx
- app/_style/Intropage/video.module.css
- app/_style/commons/commons.module.css
- app/_style/introPage/intro.module.css
- app/_style/mainPage/main.module.css
- app/layout.tsx
- app/main/page.tsx
- app/page.tsx
- metadata.ts
> [Style] 메인페이지 수정, intro페이지 추가

- app/_style/introPage/intro.module.css
- app/_utils/GoTopButton.tsx
- app/_utils/TextTyping.tsx
- app/layout.tsx
> [Feat #49] utils textTyping 추가, top button 로직 추가

- app/_utils/socket/socket.js
- app/chat_client/page.tsx
- package.json
- yarn.lock
closed #68
채팅 기능에 필요한 패키지 설치
기본적인 초기화 코드 작성
socket.io 서버를 열 때 httpServer를 열어야하는데 express를 열어서 연결이 안되던 문제 해결 (socket.io 문서 참고)
cors 정책에 의한 서버 접근 실패 문제 해결 (socket.io 문서 참고)
[socket.io 공식 사이트](https://socket.io/)를 참조했습니다.
> [Add/#68] - 채팅 기능에 필요한 패키지 설치 및 초기 설정

- app/chat_client/page.tsx
closed #70
채팅 기능을 실행하는데 불편함이 없을 정도의 간단한 UI 구현
> [Stlye/#70] - 채팅 기능의 스타일 구현

- app/(withoutGlobalLayout)/room/layout.tsx
- components/mafia/Setting.tsx
closed #75 
조건부 렌더링을 사용하여 구현하였으며 조건부에는 LocalUserChoices라는 state값을 사용하였습니다.
[liveKit Docs](https://docs.livekit.io/reference/components/react/component/prejoin/#Remarks)
> [Feat #75] 마이크 및 캠 설정

- app/(withoutGlobalLayout)/room/layout.tsx
> [Fix #98] 에러 처리 변경

- api/liveKitApi.ts
closed #100 
```
export async function getToken({ room, name }: MafiaRoom) {
const response = await fetch(`/livekit/get-participant-token?room=${room}&username=${name}`, {
cache: "no-store"
});
```
보완 전) cache: "no-cache"
보완 후) cache: "no-store"
요청 시 캐시 사용 금지: 브라우저는 기존 캐시된 응답을 사용하지 않고 항상 Origin Server에 새 요청을 보냅니다.
응답 캐싱 허용: Origin Server로부터 받은 응답은 캐시에 저장될 수 있습니다.
no-store:
캐시 저장 완전 금지: 어떤 경우에도 응답을 캐시에 저장하지 않습니다.
현) next.js에서 제시하는 것은 cache: "no-store"
별도 벨로그 작성) https://velog.io/@leejungoo1396/no-cache-no-store-%EC%B0%A8%EC%9D%B4
> [Refactor #100] 1차 코드 리뷰_리팩토링_최종본

- components/mafia/MafiaModal.tsx
- style/modal/modal.module.css
closed #111 
유동적인 시간에 따라 게이지 증가
```
<progress className={S.progress} value={(initialTime - count) * (100 / initialTime)} max={100}></progress>
```
> [Feat] progress bar 구현

- components/mafia/LocalParticipant.tsx
- components/mafia/MyVideoConference.tsx
- components/mafia/RemoteParticipant.tsx
- components/mainpageComponents/MainCreateRoom.tsx
- store/image-store.ts
- types/index.ts
closed #115 
해당 시간(투표 시간 및 저녁시간의 특정 직업의 능력)에 캠 클릭 시 user의 정보(id 및 nickname)을 서버에 전달 ==> 서버에서 직업 및 특정 값을 알려준다. 클라이언트에서는 정답에 대한 이미지를 띄어준다.
> [Feat] 캠 클릭 시 조건부 이미지 활성화

- app/(withGlobalLayout)/mafia_play/page.tsx
closed #120
소켓 통신을 하면서 마피아 게임에 필요한 기능들 구현
> [Feat #120] - 마피아 게임에 필요한 기능 구현 

- app/(withoutGlobalLayout)/room/[id]/page.tsx
closed #125 
```
socket.on("showModal", (title, message, timer, nickname, yesOrNo) => {
//NOTE - 밤일 경우 모든 user의 캠 및 마이크 off
if (message.indexOf("밤이 되었습니다")) {
allMediaSetting(tracks, false);
}
//NOTE - 아침일 경우 모든 user의 캠 및 마이크 on
if (message.indexOf("아침이 되었습니다")) {
allMediaSetting(tracks, true);
}
//NOTE - 투표시간일 경우 모든 user의 마이크 off
if (message.indexOf("투표해주세요")) {
allAudioSetting(tracks, false);
}
});
// 특정 user의 캠을 활성화 및 비활성화
socket.on("setCamera", (userId, isOn) => {
//NOTE -  1) 특정 유저의 track을 받아온다.
const specificUser = useParticipantTracks(sources, userId);
//NOTE -  2) 현재 방의 유저 중에 특정 user인지를 파악한다.
if (localIdentity === userId) {
//NOTE -  3) 해당 특정 유저일 경우 track 및 boolean값을 통해 캠 활성화 및 비활성화
specificUserVideoSetting(specificUser, isOn);
}
});
// 특정 user의 마이크를 활성화 및 비활성화 …
```
> [Test] socket IO 사용

- app/(withoutGlobalLayout)/room/layout.tsx
- components/layout/Footer.tsx
> [Fix #129] 3차 리팩토링 완료

- app/(withoutGlobalLayout)/login/page.tsx
- app/(withoutGlobalLayout)/register/page.tsx
- components/logIn/ErrorMessage.tsx
closed #134
- useId에 대해서 좀 더 공부해보기
> [Refactor #134] - 튜터님 코드 리뷰 사항 반영

- api/liveKitApi.ts
- app/(withGlobalLayout)/main/page.tsx
- app/(withoutGlobalLayout)/room/[id]/page.tsx
- app/(withoutGlobalLayout)/room/layout.tsx
- app/livekit/get-participant-token/route.ts
- components/mafia/MafiaPlayRooms.tsx
- components/mainpageComponents/MainCreateRoom.tsx
- hooks/useInfo.ts
- hooks/useToken.ts
- store/toggle-store.ts
- types/index.ts
closed #124 
```
//NOTE - 방 입장
socket.on("joinRoom", () => {
router.push(`/room/${roomId}`);
});
socket.on("joinRoomError", (message) => {
alert(message);
});
return () => {
socket.off("joinRoom");
socket.off("joinRoomError");
};
}, [roomId]);
//NOTE - 입장하기
const joinRoomHandler = async (item: any) => {
const isLogin = await checkUserLogIn();
const userInfo = await getUserInfo();
if (!isLogin || !userInfo) {
alert("로그인 후 입장 가능합니다.");
router.push("/login");
return;
}
setRoomId(item.room_id);
socket.emit("joinRoom", userInfo.id, item.room_id, userInfo.user_metadata.nickname);
};
```
<br/>
```Unhandled Runtime Error Error: Rendered more hooks than during the previous render 에러 발생```
에러 해석
- tanstack query의 커스텀훅인 "useGetToken"를 컴포넌트의 최상위 쪽으로 이동 시켜야한다.
- 하지만 문제는 "useUserInfo" …
> 마피아 방 입장 기능 구현 및 파일 구조 및 코드 수정

- app/(withGlobalLayout)/main/page.tsx
closed #Issue_132 
- [X ] 빠른방입장
유저 아이디와 닉네임을 가지고 빠른방 입장
> [Feat #132] 빠른입장

- components/mafia/RenderCards.tsx
closed #155 
return 문에 ui부분 보여주는 내용을 if문으로 작성했는데
if문을 없애고 이중 삼항연산자를 빼고 코드를 좀더 간결하게 만듬
> [Refactor #155] 사용자 직업카드 간결하게 정리

- components/mafia/LocalParticipant.tsx
- components/mafia/RemoteParticipant.tsx
- store/image-store.ts
- style/livekit/livekit.module.css
- types/index.ts
closed #154 
UI적으로 사용자가 게임 준비 버튼을 눌렀을때 캠 위에있는 이미지 체크 표시를 추가하였습니다.
> [Feat #154] 마피아 게임 페이지 - 사용자가 ready 버튼 클릭시 캠 위 이미지 체크 표시 추가

- components/mafia/GroupMafiaModal.tsx
- components/mafia/MafiaPlayRooms.tsx
> [Refactor #157] 마피아 게임 페이지 서버 연결 전 로직 확인 

- app/(withGlobalLayout)/main/page.tsx
> [Feat #146] 메인페이지 검색기능 구현

- components/layout/Nav.tsx
> [Feat #179] 헤더 로그인,로그아웃 기능 추가

- app/(withGlobalLayout)/main/page.tsx
- app/(withoutGlobalLayout)/login/page.tsx
- app/(withoutGlobalLayout)/page.tsx
- components/mainpageComponents/MainCreateRoom.tsx
- middleware.ts
- next.config.js
- utils/supabase/client.ts
- utils/supabase/middleware.ts
- utils/supabase/server.ts
closed #182 
```
const response = await updateSession(request);
const loginCookie = response.headers.get("x-middleware-request-cookie");
const url = request.nextUrl.pathname;
if (url == "/login" && loginCookie) {
const url = request.nextUrl.clone();
url.pathname = "/main";
return NextResponse.redirect(url);
}
if (url == "/register" && loginCookie) {
const url = request.nextUrl.clone();
url.pathname = "/main";
return NextResponse.redirect(url);
}
if (url.startsWith("/room") && (!url.endsWith("/") || !loginCookie)) {
const url = request.nextUrl.clone();
url.pathname = "/main";
return NextResponse.redirect(url);
}
```
```
const nextConfig = {
skipTrailingSlashRedirect: true
};
module.exports = nextConfig;
``````
[skipTrailingSlashRedirect middleware …
```
> [Feat #182] 전체 페이지의 조건에 따른 URL 직접 접근 방지

- app/(withGlobalLayout)/ranking/page.tsx
- types/supabase.ts
> [Feat #180] 랭킹데이터 편집

- api/liveKitApi.ts
- app/(withGlobalLayout)/main/page.tsx
- components/mafia/MafiaPlayRooms.tsx
closed #190 
임시 로그인으로 변경 및 오디오 끄기
> Test 임시 로그인으로 변경 및 오디오 끄기

- api/liveKitApi.ts
- components/mafia/JoinMafiaRoom.tsx
- components/mafia/LocalParticipant.tsx
- components/mafia/RemoteParticipant.tsx
- hooks/useToken.ts
closed #194 
**게임준비 이벤트 핸들러**
```tsx
const startGameHandler = () => {
const newIsReady = !isReady;
setIsReady(newIsReady);
socket.emit("setReady", userId, newIsReady, roomId);
};
```
**게임 준비 완료**
```tsx
socket.on("setReady", (message) => {
console.log("게임 준비", message);
setModalMessage(message);
setIsModal(true);
});
return () => {
socket.off("setReady");
};
}, []);
```
> [Feat #194] 게임 준비 완)

- app/(withoutGlobalLayout)/login/page.tsx
- app/(withoutGlobalLayout)/register/page.tsx
closed #199
로그인 및 회원가입 시 메인페이지로 이동
> [Fix #199] 로그인, 회원가입 시 메인페이지 이동 

- app/(withGlobalLayout)/ranking/page.tsx
> [Fix #189] ISR 삽입

- app/(withoutGlobalLayout)/register/page.tsx
회원가입 버튼 중복 클릭 시 오류로 정보가 수파베이스에 유입이 되지만 웹에 미적용
회원가입 버튼 클릭시 오류 미적용
> [Fix #208] 회원가입 버튼 오류 수정

- components/mafia/GroupMafiaModal.tsx
- components/mafia/JoinMafiaRoom.tsx
- components/mafia/MafiaPlayRooms.tsx
- types/index.ts
- utils/mafiaSocket/mafiaSocket.ts
closed #211 
```tsx
/NOTE - "마피아들은 고개를 들어 서로를 확인해 주세요." 모달창 띄우기
socket.on("r0ShowMafiaUserEachOther", () => {
r0ShowMafiaUserEachOther({
roomId,
userId,
setIsOpen,
setTitle,
setMessage,
setTimer,
setIsClose,
setIsOverlay,
setTimerIds
});
});
//NOTE -  마피아 유저 캠 및 오디오 On
socket.on("r0TurnMafiaUserCameraOn", async (players) => {
// const specificUser = useParticipantTracks(sources, "13cd6ea6-6a51-46fb-a434-10c42971dc87");
r0TurnMafiaUserCameraOnHandler({
tracks,
localUserId,
specificUser,
userId,
roomId,
sources,
setTimerIds
});
console.log(`카메라 켤 마피아 목록 : ${players}`);
});
//NOTE -  마피아 유저 캠 및 오디오 Off
socket.on("r0TurnMafiaUserCameraOff", async (players) => {
// const specificUser = useParticipantTracks(sources, "afd43d19-0728-4ab8-9b56-fb3220b5b285");
r0TurnMafiaUserCameraOffHandler({ …
```
>  마피아 시간의 모달창 띄우기 및 마피아 user의 카메라 세팅

- app/(withGlobalLayout)/mafia_play/page.tsx
closed #214
- 마피아 게임 플레이 서버 및 클라이언트 부분 에러 및 예외 사항 처리
- supabase의 API를 통해 SQL문을 작성할 때, 데이터에 null 값이 들어가서 에러가 발생하는 경우가 자주 있었습니다.
- SQL 문에 어떤 값이 들어가는지 자주 확인하는 습관을 가지는 것이 좋을 것 같습니다.
> [Fix #214] - 서버 및 클라이언트 에러 및 예외 사항 처리

- app/(withGlobalLayout)/main/page.tsx
- app/layout.tsx
closed #227 
메타데이터 최상위 파일 삽입
메타 데이터 삽입
> [Fix #227] 메타데이터 삽입

- components/mafia/JoinMafiaRoom.tsx
- components/mafia/LocalParticipant.tsx
- components/mafia/MafiaPlayRooms.tsx
- utils/mafiaSocket/mafiaSocket.ts
- utils/participantCamSettings/camSetting.ts
- utils/socket/socket.ts
closed #225 
마피아 게임의 밤 시간에 특정 user가 말을 할 경우 user의 마이크 효과인 indicator이 전체 user에게 보이는 현상이 발생하였고 이를 해결하기 위해 livekit docs를 찾아 disableSpeakingIndicator={true}이라는 메서드를 발견
https://docs.livekit.io/reference/components/react/hook/useparticipanttile/
> indicator 기능 추가

- app/(withGlobalLayout)/mafia_play/page.tsx
- utils/socket/socket.ts
closed #235
- 기존 코드 구조에서 서버와 클라이언트와의 송신과 수신을 하는 과정을 줄여서 코드를 단순화할 수 있음
- 에러나 버그를 많이 줄일 수 있을 것 같음
> [Fix #235] 마피아 게임 구조 변경

- app/(withGlobalLayout)/main/page.tsx
- components/mafia/LocalParticipant.tsx
- components/mafia/RemoteParticipant.tsx
- components/main/MainSkeleton.tsx
- components/main/MainVisual.tsx
- components/main/RoomListItem.tsx
- components/modal/VictoryModal.tsx
- hooks/useGetRoomsSocket.ts
- package.json
- style/mainPage/main.module.css
- types/index.ts
- utils/RoomSearch.tsx
- utils/socket/socket.ts
- yarn.lock
closed #285 
기존 소켓 이벤트를 메인페이지에 전부 불러오고 있었다. 
커스텀 훅으로 새로 만들어두었음.
```js
const mainSockets = {
enterMafia: (rooms: Tables<"room_table">[]) => {
setRooms(rooms);
},
joinRoom: () => {
if (roomId.current) {
router.push(`/room/${roomId.current}/`);
}
},
joinRoomError: (message: string) => {
isGoInClick.current = false;
toast.error(message);
},
fastJoinRoom: (room_id: string) => {
router.push(`/room/${room_id}/`);
setRoomId(room_id);
},
fastJoinRoomError: (message: string) => {
isGoInClick.current = false;
toast.error(message);
}
};
```
메인페이지 같은경우, 재사용성이 있는 search 검색기능은 컴포넌트를 새로 만들어 빼두었고
메인페이지에서 방 list 보여주는 부분도 컴포넌트 분리작업을 진행했다.
visual영역 부분 swiper슬라이드도 컴포넌트 분리작업을 진행해두었다.
```js
<MainVisual gameStartHandler={gameStartHandler} />
<ul className={S.roomList}>
{rooms.map((item) => (
<RoomListItem …
```
> [Refactor #285] - 메인페이지 리팩토링, skeleton라이브러리 추가

- components/mafia/RemoteParticipant.tsx
- types/index.ts
> [Fix #290] - interface 병합 문제 pr

- components/mafia/LocalParticipant.tsx
- components/mafia/RemoteParticipant.tsx
- components/mafia/RemoteParticipantTile.tsx
- components/mafia/SpeakTimer.tsx
- hooks/useCountDown.ts
- hooks/useModalSocket.ts
- hooks/useSocketOn.ts
- store/game-store.ts
- types/index.ts
- utils/ModalProgress.tsx
- utils/mafiaSocket/getPlayerNumber.ts
- yarn.lock
closed #300 
```tsx
const [isReady, setIsReady] = useState(false);
const { setSortPlayers } = useGameActions();
const { setOverlayReset } = useOverLayActions();
const [isStartButton, setIsStartButton] = useState(true);
const [isPlayerNumber, setIsPlayerNumber] = useState(false);
const [localPlayerNumber, setLocalPlayerNumber] = useState<number | undefined>();
//NOTE - 게임 시작
const gameStartSocket = {
gameStart: () => {
// 게임 버튼 비활성화
setIsStartButton(false);
//local, remote 이미지 초기화
setIsReady(false);
setOverlayReset();
// player 번호 부여
setIsPlayerNumber(true);
}
};
useSocketOn(gameStartSocket);
//NOTE - 게임 시작시 players의 번호 부여
if (isPlayerNumber) {
const gamePlayers = getPlayerNumber(participants);
const localPlayer = gamePlayers.find((player) => localParticipant.name === …
```
> [BugFix #300] 게임 시작 후 초기화 및 player 번호 부여

- components/mafia/JoinMafiaRoom.tsx
- components/mafia/MafiaModals.tsx
- components/mafia/MafiaPlayRooms.tsx
- components/modal/VictoryModal.tsx
- hooks/useJoinRoom.ts
closed #318 
```tsx
const [victoryPlayerNickname, setVictoryPlayerNickname] = useState<string[]>([""]);
//NOTE - 승리한 팀의 players nickname
if (currentModal === "VictoryModal") {
participant.forEach((playerInfo) => {
const playerJob = getPlayerJob(role, playerInfo.identity);
//시민, 의사, 경찰 승리일 경우
if (title === "citizen" && (playerJob === "citizen" || playerJob === "police" || playerJob === "doctor")) {
// playerInfo.name이 undefined가 아닌지 확인
setVictoryPlayerNickname((prevPlayers) => [...prevPlayers, playerInfo.name!]);
return;
}
//마피아일 경우
if (title === "mafia" && playerJob === "mafia") {
// playerInfo.name이 undefined가 아닌지 확인
setVictoryPlayerNickname((prevPlayers) => [...prevPlayers, playerInfo.name!]);
}
});
}
}, [currentModal]);
```
``` tsx
const getPlayerJob = (role: Role, …
```
> [Fix 318] 승리한 팀의 players nickname 표시 및 token 발급 에러 및 미디어 비활성화 처리

- components/mafia/JoinMafiaRoom.tsx
- hooks/useJoinRoom.ts
- utils/socket/socket.ts
> [Test #325] 최종 테스트 수정 병합 완료

- components/mafia/GameStartButton.tsx
- components/mafia/LocalParticipant.tsx
- components/mafia/MafiaModals.tsx
- components/mafia/MafiaPlayRooms.tsx
- components/mafia/RemoteParticipantTile.tsx
- hooks/useClickHandler.ts
- hooks/useMediaDevice.ts
- hooks/usePlayerNumber.ts
- store/game-store.ts
- types/index.ts
closed #330 
useMediaSocket을 useMediaDevice로 변경 및 로직 변경
```tsx
import { MediaStatus } from "@/types";
import { useLocalParticipant, useRemoteParticipants, useTracks } from "@livekit/components-react";
import { Track } from "livekit-client";
import { useEffect, useState } from "react";
//NOTE - playersMedias 구조: {userId: {cam: boolean, mike: boolean}}
const useMediaDevice = () => {
const [playersMediaStatus, setPlayersMediaStatus] = useState<MediaStatus | null>(null);
const [isMediaReset, setIsMediaReset] = useState(false);
...
//NOTE - 게임 종료 시 모든 player 캠 및 오디오 on
if (isMediaReset) {
console.log("🚀게임 종료 시 AllPlayer 미디어 On:", isMediaReset);
//로컬 사용자의 미디어
if (localPlayerId) {
const localCamera = localParticipant.cameraTrack?.track?.mediaStreamTrack;
const localMike = …
```
> [bugFix 330] 게임 종료 시 미디어 초기화

- components/mafia/MafiaPlayRooms.tsx
- hooks/useJoinRoomSocket.ts
- utils/mafiaSocket/getPlayersNumber.ts
- utils/socket/socket.ts
closed #335
- server 코드 자바스크립트에서 타입스크립트로 변환
- 타입 스크립트 tsconfig.ts 설정 문제
- ts-node를 사용해서 컴파일과 동시에 실행
- nodemon을 사용해서 실행 중 저장하면 자동으로 코드 최신화
[타입스크립트 설정 참고](https://bgradecoding.tistory.com/26)
> [Refactor #335] 게임이 끝나고 UI가 초기화 되지 않는 현상 수정

- api/liveKitApi.ts
- app/(withGlobalLayout)/main/page.tsx
- app/livekit/get-participant-token/route.ts
- components/mafia/GameStartButton.tsx
- components/mafia/JoinMafiaRoom.tsx
- components/mafia/MafiaModals.tsx
- components/mafia/MafiaPlayRooms.tsx
- components/modal/CheckModal.tsx
- components/modal/VictoryModal.tsx
- hooks/useGetRoomsSocket.ts
- hooks/useJoinRoom.ts
- hooks/useJoinRoomSocket.ts
- hooks/useMediaDevice.ts
- hooks/useSearchDebounce.ts
- hooks/useSelectSocket.ts
- hooks/useToken.ts
- middleware.ts
- store/connect-store.ts
- types/index.ts
- utils/FormSearch.tsx
- utils/ModalConfetti.tsx
- utils/reload/useBeforeUnloadHandler.ts
- utils/socket/socket.ts
- utils/supabase/authAPI.ts
- utils/supabase/middleware.ts
closed #339 
- 게임 상태의 전역 state값인 ``gameState``를 승리의 모달 컴포넌트 종료 시 ``"gameEnd"``로 변경하여, ``MafiaPlayRooms``라는 상위컴포넌트에서 게임 종료 로직 처리
>**승리 모달창에서 게임 종료 로직을 처리하지 않은 이유**
> - ``게임 입장 시 초기화, 게임 실행, 죽은 player 관리, Error 처리 등`` 중앙 컨트롤 역할을 담당하는 ``MafiaPlayRooms`` 컴포넌트에서 처리하고 있으므로 유지보수 및 가독성 측면에서 전역 state값을 활용하여, 중앙에서 같이 처리하는 게 맞다고 판단
MafiaPlayRooms.tsx
```tsx
const MafiaPlayRooms = () => {
const isGameState = useGameState();
...
//NOTE - 게임 종료
if (isGameState === "gameEnd") {
console.log("🚀 isGameState:", isGameState);
setOverlayReset(); //Local,Remote 클릭 이벤트 및 캠 이미지 초기화
setModalReset(); //전체 모달 요소 초기화
setGameReset(); // 죽은 players 및 게임 state 초기화
setIsMediaReset(true); // 캠 및 오디오 초기화
}
}, [isGameState]);
...
}
```
VictoryModal.tsx
```tsx
const VictoryModal = () => {
const title = …
```
> [Fix #339] 마피아페이지 코드 정리 및 모달창 progressbar 수정

- app/globals.css
- components/layout/Nav.tsx
- components/main/MainVisual.tsx
- hooks/useJoinRoom.ts
- style/Intropage/intro.module.css
- style/commons/commons.module.css
- style/login/login.module.css
- style/mainPage/main.module.css
- style/mainPage/swiper.css
- style/ranking/ranking.module.css
- style/register/register.module.css
closed #350 
css요소로 개발 내용이 아니기 떄문에 생략하겠습니다.
> [Style #350] - 전체페이지 반응형 수정

- app/(withGlobalLayout)/layout.tsx
- app/(withGlobalLayout)/mafiainfo/page.tsx
- components/mafia/MafiaModals.tsx
- components/modal/GroupMafiaModal.tsx
- components/modal/LastVoteResultModal.tsx
- components/modal/VoteResultModal.tsx
- store/overlay-store.ts
- store/toggle-store.ts
- style/mafiaInfo/mafiaInfo.module.css
- style/ranking/ranking.module.css
> [Style #353] - CSS 반응형 수정

- app/(withoutGlobalLayout)/page.tsx
> [Fix #365] ios환경 영상 안보이게 수정

- components/layout/Nav.tsx
- components/ranking/MyRanking.tsx
- components/ranking/Pagination.tsx
- style/mafiaInfo/mafiaInfo.module.css
- style/ranking/ranking.module.css
- utils/socket/socket.ts
> [Fix #372] - nav 반응형 진입 시 랭킹페이지 이동 수정, 반응형 수정

- components/mafia/MafiaPlayRooms.tsx
- style/modal/modal.module.css
- style/ranking/ranking.module.css
> [Fix #374] - 랭킹페이지 반응형 진입 시 word 깨지는 현상 수정

- app/(withGlobalLayout)/ranking/page.tsx
- app/(withoutGlobalLayout)/page.tsx
- components/layout/Footer.tsx
- components/layout/Header.tsx
- components/layout/Nav.tsx
- components/main/CreateRoomModal.tsx
- components/main/MainCreateRoom.tsx
- components/ranking/MyRanking.tsx
- hooks/useJoinRoom.ts
- tsconfig.json
- utils/GoTopButton.tsx
- utils/supabase/authAPI.ts
> [Test #417] 로그인 및 메인페이지 CreateModal JoinRoom socket 중복 제거

- components/mafia/JoinMafiaRoom.tsx
> [bugFix #421] 방 입장 에러 확인

- components/mafia/JoinMafiaRoom.tsx
- components/mafia/MafiaHeader.tsx
- components/mafia/MafiaModals.tsx
- components/mafia/MafiaPlayRooms.tsx
- utils/socket/socket.ts
closed #425 
[LiveKit 레퍼런스](https://github.dev/livekit-examples/meet)
> [bugfix #425] 방 입장 후 미디어 장치 접근 제한 설정
